services:
  # --- Frontend ---
  # --- DEPRECATED ---
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    env_file: ${ENV_FILE:-.env}
    environment:
      - NEXT_PUBLIC_GATEWAY_URL=http://gateway:4000/graphql
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_APP_MODE=${NEXT_PUBLIC_APP_MODE:-demo}
      - NEXT_PUBLIC_INSIGHT_TIMEOUT=${NEXT_PUBLIC_INSIGHT_TIMEOUT:-240000}
    networks:
      - mindmirror-network
    depends_on:
      gateway:
        condition: service_healthy
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # --- Backend Services ---
  agent_service:
    build:
      context: .
      dockerfile: src/agent_service/Dockerfile
    container_name: agent_service
    env_file: ${ENV_FILE:-.env}
    environment:
      # Prompt Storage Configuration
      - PROMPT_STORAGE_TYPE=${PROMPT_STORAGE_TYPE:-gcs}
      - YAML_STORAGE_PATH=${YAML_STORAGE_PATH:-/app/prompts}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME:-}
      - GCS_CREDENTIALS_FILE=${GCS_CREDENTIALS_FILE:-}
      - GCS_EMULATOR_HOST=${GCS_EMULATOR_HOST:-}
      # GCS Configuration - Only set emulator host if USE_GCS_EMULATOR is true
      - STORAGE_EMULATOR_HOST=${STORAGE_EMULATOR_HOST:-}
      - TRADITION_DISCOVERY_MODE=${TRADITION_DISCOVERY_MODE:-}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT:-mindmirror-69}
    volumes:
      - ./src/agent_service:/app/agent_service
      - ./local_gcs_bucket:/app/local_gcs_bucket:ro  # Read-only local files
      - gcs_emulator_data:/app/gcs_data              # GCS emulator storage
      # Mount local Google Cloud credentials for real GCS access
      - ~/.config/gcloud:/root/.config/gcloud:ro
    command: uvicorn agent_service.app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - mindmirror-network
    depends_on:
      - postgres
      - qdrant
      - redis
      - gcs-emulator
    ports:
      - "8000:8000" # Expose for direct access during dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1s
      timeout: 20s
      retries: 10
      start_period: 5s

  journal_service:
    build:
      context: .
      dockerfile: src/journal_service/Dockerfile
    container_name: journal_service
    env_file: ${ENV_FILE:-.env}
    environment:
      # Override DATABASE_URL to use local Postgres for development
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/cyborg_coach
      # Explicitly set the environment to local for Docker development
      - ENVIRONMENT=local
      # GCS Configuration - Only set emulator host if USE_GCS_EMULATOR is true
      - STORAGE_EMULATOR_HOST=${STORAGE_EMULATOR_HOST:-}
      - TRADITION_DISCOVERY_MODE=${TRADITION_DISCOVERY_MODE:-}
    volumes:
      - ./src/journal_service:/app/journal_service
      - ./local_gcs_bucket:/app/local_gcs_bucket:ro  # Read-only local files
      - gcs_emulator_data:/app/gcs_data              # GCS emulator storage
      # Mount local Google Cloud credentials for real GCS access
      - ~/.config/gcloud:/root/.config/gcloud:ro
    command: uvicorn journal_service.journal_service.main:app --host 0.0.0.0 --port 8001 --reload
    networks:
      - mindmirror-network
    depends_on:
      - postgres
      - redis
      - gcs-emulator
    ports:
      - "8001:8001" # Expose for direct access during dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 1s
      timeout: 20s
      retries: 10
      start_period: 5s
      
  # --- Workers ---
  celery-worker-web:
    build:
      context: .
      dockerfile: celery-worker/Dockerfile
    container_name: celery-worker-web
    env_file: ${ENV_FILE:-.env}
    environment:
      # Prompt Storage Configuration
      - PROMPT_STORAGE_TYPE=${PROMPT_STORAGE_TYPE:-gcs}
      - YAML_STORAGE_PATH=${YAML_STORAGE_PATH:-/app/prompts}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME:-}
      - GCS_CREDENTIALS_FILE=${GCS_CREDENTIALS_FILE:-}
      - GCS_EMULATOR_HOST=${GCS_EMULATOR_HOST:-}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - QDRANT_URL=${QDRANT_URL:-http://qdrant:6333}
      - JOURNAL_SERVICE_URL=${JOURNAL_SERVICE_URL:-http://journal_service:8001}
      - REINDEX_SECRET_KEY=${REINDEX_SECRET_KEY:-dev-secret-key}
      # GCS Configuration - Only set emulator host if USE_GCS_EMULATOR is true
      - STORAGE_EMULATOR_HOST=${STORAGE_EMULATOR_HOST:-}
      - TRADITION_DISCOVERY_MODE=${TRADITION_DISCOVERY_MODE:-}
      - RUN_MODE=web
    volumes:
      - ./celery-worker:/app
      - ./ingestion:/app/ingestion
      - ./local_gcs_bucket:/app/local_gcs_bucket:ro  # Read-only local files
      - gcs_emulator_data:/app/gcs_data              # GCS emulator storage
      # Mount local Google Cloud credentials for real GCS access
      - ~/.config/gcloud:/root/.config/gcloud:ro
    command: ["./start-web.sh"]
    networks:
      - mindmirror-network
    depends_on:
      - redis
      - postgres
      - qdrant
      - journal_service
      - gcs-emulator
    ports:
      - "8002:8000" # Expose for direct access during dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery-worker:
    build:
      context: .
      dockerfile: celery-worker/Dockerfile
    container_name: celery-worker
    env_file: ${ENV_FILE:-.env}
    environment:
      # Prompt Storage Configuration
      - PROMPT_STORAGE_TYPE=${PROMPT_STORAGE_TYPE:-gcs}
      - YAML_STORAGE_PATH=${YAML_STORAGE_PATH:-/app/prompts}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME:-}
      - GCS_CREDENTIALS_FILE=${GCS_CREDENTIALS_FILE:-}
      - GCS_EMULATOR_HOST=${GCS_EMULATOR_HOST:-}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - QDRANT_URL=${QDRANT_URL:-http://qdrant:6333}
      - JOURNAL_SERVICE_URL=${JOURNAL_SERVICE_URL:-http://journal_service:8001}
      - REINDEX_SECRET_KEY=${REINDEX_SECRET_KEY:-dev-secret-key}
      # GCS Configuration - Only set emulator host if USE_GCS_EMULATOR is true
      - STORAGE_EMULATOR_HOST=${STORAGE_EMULATOR_HOST:-}
      - TRADITION_DISCOVERY_MODE=${TRADITION_DISCOVERY_MODE:-}
      - RUN_MODE=worker
    volumes:
      - ./celery-worker:/app
      - ./ingestion:/app/ingestion
      - ./local_gcs_bucket:/app/local_gcs_bucket:ro  # Read-only local files
      - gcs_emulator_data:/app/gcs_data              # GCS emulator storage
      # Mount local Google Cloud credentials for real GCS access
      - ~/.config/gcloud:/root/.config/gcloud:ro
    command: ["./start-worker.sh"]
    networks:
      - mindmirror-network
    depends_on:
      - redis
      - postgres
      - qdrant
      - journal_service
      - gcs-emulator

  celery_flower:
    image: mher/flower:2.0
    container_name: celery_flower
    environment:
      - CELERY_BROKER_URL=${REDIS_URL}
    env_file: ${ENV_FILE:-.env}
    networks:
      - mindmirror-network
    ports:
      - "5555:5555"
    depends_on:
      - redis

  # --- GCS Emulator (Development Only) ---
  gcs-emulator:
    image: fsouza/fake-gcs-server:latest
    container_name: gcs-emulator
    ports:
      - "4443:4443"
    volumes:
      - ./local_gcs_bucket:/data:ro  # Preload local files into emulator
    command: ["-scheme", "http", "-port", "4443"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4443/storage/v1/b"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - mindmirror-network

  # --- Databases & Infrastructure ---
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mindmirror-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - mindmirror-network
    volumes:
      - qdrant_data:/qdrant/storage
    # The official qdrant image is distroless and has no shell,
    # so we can't use a command-based healthcheck.
    # We rely on service_started condition.

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mindmirror-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  mesh-compose:
    build:
      context: ./mesh
      dockerfile: Dockerfile.mesh-compose
    command: ["bash", "-c", "npx mesh-compose -o build/supergraph.graphql"]
    volumes:
      - ./mesh/build:/app/build
    networks:
      - mindmirror-network
    depends_on:
      journal_service:
        condition: service_healthy
      agent_service:
        condition: service_healthy

  gateway:
    build:
      context: ./mesh
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
    env_file:
      - ${ENV_FILE:-.env}
    volumes:
      - ./mesh/gateway.config.ts:/app/gateway.config.ts
      - ./mesh/build:/app/build
    networks:
      - mindmirror-network
    depends_on:
      mesh-compose:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/healthcheck"]
      interval: 2s
      timeout: 10s
      retries: 20
      start_period: 5s

volumes:
  postgres_data:
  qdrant_data:
  gcs_emulator_data:  # Renamed for clarity
  prompts_data:
    driver: local

networks:
  mindmirror-network:
    driver: bridge
