services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - I_AM_IN_A_DOCKER_CONTAINER=1
    command: >
      sh -c "poetry run python scripts/build_knowledge_base.py &&
             poetry run uvicorn api:app --host 0.0.0.0 --port 8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/graphql"]
      interval: 15s
      timeout: 10s
      retries: 10

  ui:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - API_HOST=api
      - I_AM_IN_A_DOCKER_CONTAINER=1
    command: poetry run streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      api:
        condition: service_healthy
