[tool.poetry]
name = "librarian-ai"
version = "0.1.0"
description = "Your Personal AI-Powered Library Agent"
authors = ["Gemini"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
langchain = "^0.3.25"
langgraph = "^0.4.8"
langchain-experimental = "^0.3.4"
langchain-openai = "^0.3.21"
langchain-community = "^0.3.24"
faiss-cpu = "^1.11.0"
tiktoken = "^0.9.0"
networkx = "^3.5"
pypdf = "^5.6.0"
pymupdf = "^1.26.0"
python-dotenv = "^1.1.0"
requests = "^2.32.4"
streamlit = "^1.45.1"
aiohttp = "^3.12.12"
pytest-asyncio = "^1.0.0"
langchain-ollama = "^0.3.3"


[tool.poetry.group.dev.dependencies]
pytest = "^8.4.0"
pytest-mock = "^3.14.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
