name: Local Build Test

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Service to build (agent_service, journal_service, habits_service, meals_service, movements_service, celery-worker, mesh, all)"
        required: true
        default: "all"

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      # Default production service URLs (can be overridden)
      JOURNAL_SERVICE_URL: https://journal-service-3858903851.us-east4.run.app
      AGENT_SERVICE_URL: https://agent-service-3858903851.us-east4.run.app
      HABITS_SERVICE_URL: https://habits-service-3858903851.us-east4.run.app
      MEALS_SERVICE_URL: https://meals-service-3858903851.us-east4.run.app
      PRACTICES_SERVICE_URL: https://practices-service-3858903851.us-east4.run.app
      MOVEMENTS_SERVICE_URL: https://movements-service-3858903851.us-east4.run.app
      USERS_SERVICE_URL: https://users-service-3858903851.us-east4.run.app
      # Vouchers Web Base (used by Mesh OpenAPI subgraph for vouchers/autoenroll)
      VOUCHERS_WEB_BASE_URL: https://mind-mirror-seven.vercel.app

    steps:
      - uses: actions/checkout@v4

      - name: Select Build Target
        id: select
        run: |
          echo "service=${{ github.event.inputs.service }}" >> $GITHUB_ENV
          echo "tag=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Docker build agent_service
        if: env.service == 'agent_service' || env.service == 'all'
        run: |
          docker build -t us-east4-docker.pkg.dev/mindmirror-69/mindmirror/agent_service:${{ env.tag }} -f src/agent_service/Dockerfile .

      - name: Echo push command for agent_service
        if: env.service == 'agent_service' || env.service == 'all'
        run: |
          echo "Build complete. To push the image, run:"
          echo "docker push us-east4-docker.pkg.dev/mindmirror-69/mindmirror/agent_service:${{ env.tag }}"
          echo "::notice title=agent_service image tag::us-east4-docker.pkg.dev/mindmirror-69/mindmirror/agent_service:${{ env.tag }}"

      - name: Docker build journal_service
        if: env.service == 'journal_service' || env.service == 'all'
        run: |
          docker build -t us-east4-docker.pkg.dev/mindmirror-69/mindmirror/journal_service:${{ env.tag }} -f src/journal_service/Dockerfile .

      - name: Echo push command for journal_service
        if: env.service == 'journal_service' || env.service == 'all'
        run: |
          echo "Build complete. To push the image, run:"
          echo "docker push us-east4-docker.pkg.dev/mindmirror-69/mindmirror/journal_service:${{ env.tag }}"
          echo "::notice title=journal_service image tag::us-east4-docker.pkg.dev/mindmirror-69/mindmirror/journal_service:${{ env.tag }}"

      - name: Docker build habits_service (prod deps)
        if: env.service == 'habits_service' || env.service == 'all'
        run: |
          docker build \
            --build-arg BUILD_WITH_DEV=false \
            -t us-east4-docker.pkg.dev/mindmirror-69/mindmirror/habits_service:${{ env.tag }} \
            -f habits_service/Dockerfile .

      - name: Echo push command for habits_service
        if: env.service == 'habits_service' || env.service == 'all'
        run: |
          echo "Build complete. To push the image, run:"
          echo "docker push us-east4-docker.pkg.dev/mindmirror-69/mindmirror/habits_service:${{ env.tag }}"
          echo "::notice title=habits_service image tag::us-east4-docker.pkg.dev/mindmirror-69/mindmirror/habits_service:${{ env.tag }}"

      - name: Docker build meals_service
        if: env.service == 'meals_service' || env.service == 'all'
        run: |
          docker build -t us-east4-docker.pkg.dev/mindmirror-69/mindmirror/meals_service:${{ env.tag }} -f meals_service/Dockerfile ./meals_service

      - name: Echo push command for meals_service
        if: env.service == 'meals_service' || env.service == 'all'
        run: |
          echo "Build complete. To push the image, run:"
          echo "docker push us-east4-docker.pkg.dev/mindmirror-69/mindmirror/meals_service:${{ env.tag }}"
          echo "::notice title=meals_service image tag::us-east4-docker.pkg.dev/mindmirror-69/mindmirror/meals_service:${{ env.tag }}"

      - name: Docker build users_service
        if: env.service == 'users_service' || env.service == 'all'
        run: |
          docker build -t us-east4-docker.pkg.dev/mindmirror-69/mindmirror/users_service:${{ env.tag }} -f users_service/Dockerfile ./users_service

      - name: Echo push command for users_service
        if: env.service == 'users_service' || env.service == 'all'
        run: |
          echo "Build complete. To push the image, run:"
          echo "docker push us-east4-docker.pkg.dev/mindmirror-69/mindmirror/users_service:${{ env.tag }}"
          echo "::notice title=users_service image tag::us-east4-docker.pkg.dev/mindmirror-69/mindmirror/users_service:${{ env.tag }}"

      - name: Docker build movements_service
        if: env.service == 'movements_service' || env.service == 'all'
        run: |
          docker build -t us-east4-docker.pkg.dev/mindmirror-69/mindmirror/movements_service:${{ env.tag }} -f movements_service/Dockerfile ./movements_service

      - name: Echo push command for movements_service
        if: env.service == 'movements_service' || env.service == 'all'
        run: |
          echo "Build complete. To push the image, run:"
          echo "docker push us-east4-docker.pkg.dev/mindmirror-69/mindmirror/movements_service:${{ env.tag }}"
          echo "::notice title=movements_service image tag::us-east4-docker.pkg.dev/mindmirror-69/mindmirror/movements_service:${{ env.tag }}"

      - name: Docker build practices_service (prod)
        if: env.service == 'practices_service' || env.service == 'all'
        run: |
          docker build \
            --build-arg PROD=1 \
            -t us-east4-docker.pkg.dev/mindmirror-69/mindmirror/practices_service:${{ env.tag }} \
            -f practices_service/Dockerfile .

      - name: Echo push command for practices_service
        if: env.service == 'practices_service' || env.service == 'all'
        run: |
          echo "Build complete. To push the image, run:"
          echo "docker push us-east4-docker.pkg.dev/mindmirror-69/mindmirror/practices_service:${{ env.tag }}"
          echo "::notice title=practices_service image tag::us-east4-docker.pkg.dev/mindmirror-69/mindmirror/practices_service:${{ env.tag }}"

      - name: Docker build celery-worker
        if: env.service == 'celery-worker' || env.service == 'all'
        run: |
          docker build -t us-east4-docker.pkg.dev/mindmirror-69/mindmirror/celery-worker:${{ env.tag }} -f celery-worker/Dockerfile .

      - name: Echo push command for celery-worker
        if: env.service == 'celery-worker' || env.service == 'all'
        run: |
          echo "Build complete. To push the image, run:"
          echo "docker push us-east4-docker.pkg.dev/mindmirror-69/mindmirror/celery-worker:${{ env.tag }}"
          echo "::notice title=celery-worker image tag::us-east4-docker.pkg.dev/mindmirror-69/mindmirror/celery-worker:${{ env.tag }}"

      - name: Build supergraph with mesh-compose
        if: env.service == 'mesh' || env.service == 'all'
        run: |
          # Build the mesh-compose image
          docker build \
            -f mesh/Dockerfile.mesh-compose \
            -t us-east4-docker.pkg.dev/mindmirror-69/mindmirror/mesh-compose:${{ env.tag }} \
            ./mesh
          echo "Build complete. To push the image, run:"
          echo "docker push us-east4-docker.pkg.dev/mindmirror-69/mindmirror/mesh-compose:${{ env.tag }}"
          echo "::notice title=mesh-compose image tag::us-east4-docker.pkg.dev/mindmirror-69/mindmirror/mesh-compose:${{ env.tag }}"
            
          # Run the container to generate the supergraph, saving it to the local filesystem
          docker run --rm \
            -v $(pwd)/mesh/build:/app/build \
            --env JOURNAL_SERVICE_URL=${JOURNAL_SERVICE_URL:-https://journal-service-3858903851.us-east4.run.app} \
            --env AGENT_SERVICE_URL=${AGENT_SERVICE_URL:-https://agent-service-3858903851.us-east4.run.app} \
            --env HABITS_SERVICE_URL=${HABITS_SERVICE_URL:-https://habits-service-3858903851.us-east4.run.app} \
            --env MEALS_SERVICE_URL=${MEALS_SERVICE_URL:-https://meals-service-3858903851.us-east4.run.app} \
            --env PRACTICES_SERVICE_URL=${PRACTICES_SERVICE_URL:-https://practices-service-3858903851.us-east4.run.app} \
            --env MOVEMENTS_SERVICE_URL=${MOVEMENTS_SERVICE_URL:-https://movements-service-3858903851.us-east4.run.app} \
            --env USERS_SERVICE_URL=${USERS_SERVICE_URL:-https://users-service-3858903851.us-east4.run.app} \
            --env VOUCHERS_WEB_BASE_URL=${VOUCHERS_WEB_BASE_URL:-https://mind-mirror-seven.vercel.app} \
            us-east4-docker.pkg.dev/mindmirror-69/mindmirror/mesh-compose:${{ env.tag }} \
            sh -lc "npx mesh-compose -c mesh.config.dynamic.ts -o /app/build/supergraph.graphql && ls -la /app/build"

      - name: Docker build mesh (with generated supergraph)
        if: env.service == 'mesh' || env.service == 'all'
        run: |
          # Build the final mesh container with the production supergraph now available locally
          docker build -t us-east4-docker.pkg.dev/mindmirror-69/mindmirror/mesh:${{ env.tag }} -f mesh/Dockerfile ./mesh
          echo "Build complete. To push the image, run:"
          echo "docker push us-east4-docker.pkg.dev/mindmirror-69/mindmirror/mesh:${{ env.tag }}"
          echo "::notice title=mesh image tag::us-east4-docker.pkg.dev/mindmirror-69/mindmirror/mesh:${{ env.tag }}"
